### PR TITLE
User context - Private routes - Admin view

### PR DESCRIPTION
**Pull request by Abdulla-Alkhulaqui**
Added user context (i.e. all the application is able to access user data).
Added private routes:
- If user is not logged in, they will be redirected to the login page if they tried to access any route.
- If the user is logged in, they will be redirected to the profile page if they tried to access the login page.

Added admin view (@RealGorandos )
- The admin main view is not implemented in the frontend.

### CODE REVIEW

**Comment by the4t4** [comment]
The frontend is commented out from docker compose and nginx

**Comment by Mohido** [comment]
Yeah it is made that way because it was crashing the nginx server @the4t4 .

**Comment by the4t4** [comment]
why is it crashing nginx

**Comment by Mohido** [comment]
I don't know.. Haven't looked into that. Mostly the built image exits once it is run leading to crashing the nginx. @the4t4

**Pull request merged**
